#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: title:t toc:t todo:t |:t
#+TITLE: Measure_samples
#+DATE: <2016-08-10 Wed>
#+AUTHOR:
#+EMAIL: joaquin@joaquin_laptop
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.4)


* Introduction
This file is a try to document and enhance the program in python to measure the samples through the mechanism of of break-junction in gold samples for the study of molecular properties.
The reason for this is that the current program, while functional is underdocumented and the full how-to is preserved through *oral tradition* which is regrettable for an investigation lab, and since the author of this document has a bit of experience in software development and documentation, this file was born.

** Break Junction
The experiment is to measure the break junction


**  Actuators and measuremnts
The program uses 2 different mechanical actuators to perform the measurements, and there are 2 different kind of samples to be measured. Finally the measurement is performed by analyzing the conductance of the sample.

*** Mechanical actuators
Since the experiment is based on a single gold "nano-wire"  which is broken through mechanical means, there is need for mechanical acutators to beak the "wire" to measure the conductance change.

**** Faulhaber Motor
The Faulhaber motor is used to perform relatively large movements on the sample and is used to break the sample initially

**** Piezo actuator
Once the junction is broken, the motor is turned off and the piezo-device is used, since it provides a simple controllable way to perform even samller movements on the piece for the study

*** Samples types
Even though the experiment is always performed over gold "wires", there are 2 distinct clasification of the samples.
# So far it seems (to me) that regardless of the type of measurement the mechanism is the same
**** Clean gold
Since the gold is the sustrate, is measured to ensure that is clean and there are no impurities prior to a real measurement

**** Gold + Molecule
The focus of the experiment is to measure the transport (conductance) properties of a given molecule, thus once a gold sustrate has been measured and confirmed to be usable, a molecule solution is placed on the sustrate with the expectation that a molecule gets inserted in the gap between the gold terminals.

*** ADWin mesurement
The measurement of the conductance is performed using the ADWin board which has an interface and binding to python. The documentation for the ADWin measurement instrument can be found on the [[http://www.adwin.de/us/download/linux.html][Download page]]

Since the objective is to measure the transport properties, the most important parameters to measure are the conductance and the separation between the gold contacts (break junction)


* Program Description
As it was already stated the measurement is splitted in 2 steps, the motor initialization and the piezo measurement, however a full program cannot be limited to these 2 steps, as there are additional requirements uch as a user interface for the program. Thus the program is organized as:
- Main loop :: As in many programs the main loop is the one that orchestrates the execution of the program. For details see [[Main loop]]
- UI Interface :: Considering the requiremens for different configurations for the measurement such as the voltage applied to the juncture, there is a requierement for a reasonable to use UI, and this UI should allow the user to run a measurement. For details see [[User Interface]]
- motor break :: Using the motor actuator, a break juncture is created and then the displacement is set so that a movement generated with the piezo-electric actuator the juncture can be easily reconstructed. For details see [[Motor break junction]]
- Measurement with the piezo :: With the sample in the optimal setting for the piezo is the measured by modifying the voltage applied to the piezo-electric device which in turn creates a displacement of the sample recreating the juncture an allowing for easily repetable measurements through the dynamic range of the piezo-electric device. For details see [[Measurement with Piezo]]

Obviously there is a series of additional modules which provide the interface to the different actuators, and additional helpeer functions to improve the presentation of the results, all of which will be presented in turn.

** Main Loop
   :PROPERTIES:
   :tangle:   main.py
   :END:
#+BEGIN_SRC python :exports none
  #################################################################
  ## @file    Main.py
  #  @author  Joaquin Figueroa
  #  @brief   Main file for measuring break-junction experiments
  #
  #  @details This is the main file for the program used to
  #           measure samples using the break-junction technique.
  #           This program provides a GUI to control the execution
  #           based on providing the tools to configure a run.
  #           The program automates the whole procedure by:
  #           1- Automating the creation of the break junction
  #           using the motor
  #           2- Automating the measurement process using a piezo
  #           actuator.
  #################################################################
#+END_SRC
As with many considerable programs this one stars importing the necesary files. In this case, all the modules imported for the main file come from the modules created for the program.
#+BEGIN_SRC python
  import sys
  import modules.ui_config as UI
  import modules.motor_break as MB
  import modules.piezo_measure as PM
#+END_SRC 

The main loop is indeed a loop. It is intended to work in the following way.
- First the UI is presented to the user, so the user can modify the configuration of the experiment. As a result from the UI execution there are 3 possible outcomes:
  1. Exit the program
     #+BEGIN_SRC python
       ############################################################
       ## @fn    : main_exit
       #  @brief : Terminates program execution
       ############################################################
       def main_exit() :
           print("Program Finished successfully")
           sys.exit()
     #+END_SRC
  2. Excecute only the junction creation. This is to prepare a clean sample, since there is no benefit to measure using the piezo a clean sample
     #+BEGIN_SRC python
       ############################################################
       ## @fn      : main_motor_break
       #  @details : Commands the motor to break the gold channel
       #             creating a break-junction and then joins it
       #             again leaving it ready for measurement
       ############################################################
       def main_motor_break():
           MB.motor_break_juncture()
     #+END_SRC
  3. Execute a full measurement, creating the juncture and then measure the molecule
     #+BEGIN_SRC python
       ############################################################
       ## @fn      : main_measure
       #  @details : Measures the transport properties of the
       #             sample by creating the break-junction with the
       #             motor, and using the piezo to measure
       ############################################################
       def main_measure():
           MB.motor_break_juncture()
           PM.measure_sample()
     #+END_SRC

The outcome picked by the user must be translated into a command in the program, this is performed in a similar way as a switch-case, but in python is implemented as a dictionary test, which may seem odd for someone not used to the technique. For reference please see [[http://www.pydanny.com/why-doesnt-python-have-switch-case.html][switch-case in python.]]
#+BEGIN_SRC python
  ############################################################
  ## @fn      : execute_ui_cmd
  #  @details : Analyzed the command chosen by the user and
  #             executes it. Options are:
  #             1- End program
  #             2- only perform break-junction
  #             3- perform full measurement of the sample
  ############################################################
  def execute_ui_cmd(ui_cmd) :
      switch = {
          UI.CMD.EXIT    : main_exit,
          UI.CMD.M_BREAK : main_motor_break,
          UI.CMD.MEASURE : main_measure,
      }
      cmd = switch.get(ui_cmd, sys.exit)
      cmd()
#+END_SRC

Finally the main loop is executed indefinitely until the user terminates the program

#+BEGIN_SRC python
  ############################################################
  ## @details : Main loop. Executes UI Cmd until the user end
  ##            the program
  ############################################################
  while True :
      ui_cmd=UI.CMD.EXIT
      execute_ui_cmd(ui_cmd)
#+END_SRC

** User Interface
   :PROPERTIES:
   :tangle:   modules/ui_config.py
   :END:
# As with any module there is a section for the imports and the file headers, but these are unninteresting for any reader, thus they are put in comments and not exported to a PDF/HTML result
#+BEGIN_SRC python :exports none
  #################################################################
  ## @file    ui_config.py
  #  @author  Joaquin Figueroa
  #  @date    Fri Aug 12 2016
  #  @brief   Provides a UI for configuring the experiment
  #
  #  @details This file provides a GUI for the user to be able to
  #           configure the experiment and run it.
  #################################################################
  from PyQt4 import QtGui
#+END_SRC

The user interface has 2 requirements.
1. It should allow the user to run the experiment
2. It should allow the user to tweak with the configuration for the experiment

Now there is an additional requirement for the UI, which is the interface by itself, thus the UI module can be thought as the result of 2 pieces.
- Program Interface :: The UI - program interface is how the UI interacts with the rest of the program. See [[UI - Program Interface]]
- GUI :: The graphical User interface is how the program interacts with the user. See [[UI - GUI]]

*** UI - Program Interface
 Therefore the output of the UI execution is a tuple with one value being the command to be executed, and the other the configuration for the measurements.
 #+BEGIN_SRC python
   ############################################################
   ## @class   UI_RESULT
   #  @details This class has the return type of the UI class
   #           The return type has:
   #           1- Command to be executed (exit, measure)
   #           2- Configuration for the measurements
   ############################################################
   class UI_RESULT:
       def __init__(self, cmd, config):
           self.cmd    = cmd
           self.config = config
 #+END_SRC

**** UI command
  Now the command to be executed has only a few possible values, which are used to, as previously explained, to terminate the program, or execute one of the routines.
  #+BEGIN_SRC python
    ############################################################
    ## @class  CMD
    #  @brief  UI calss to encode the possible commands for the
    #         program
    ############################################################
    class CMD:
        EXIT    = 0
        M_BREAK = 1
        MEASURE = 2
  #+END_SRC 

**** UI Configuration
     :PROPERTIES:
     :noweb:    yes
     :END:
The UI configuration is a list of variables which are used through the measurements for configuring the experiments or for controlling the presentation of the results, for simplicity the variables are classified in groups
- Basic parameters :: These are the parameters that control the run and define it see [[UI - Basic parameters ]]
- Advanced parameters :: There are more advanced parameters that influence the run, but have minor impact (usually) when compared with the other parameters, and the user is rarely ever expected to modify them. See [[UI - Advanced paramenter ]]
- Presentation parameters :: The results of the experiment is processed in graph; some of the parameters for the graph can be tweaked to improve the readability of them. See [[UI - Presentation]]

#+BEGIN_SRC python
  ############################################################
  ## @class   UI_CONFIG
  #  @details This class stores all configuration values to be
  #           used for the measurements.
  ############################################################
  class UI_CONFIG:
      def __init__(self):
          self._basic_param = basic_params()
          self._adv_param = adv_param()
          self._presentation = presentation()

      <<ui-config-bp-interface>>
      <<ui-config-ap-interface>>
      <<ui-config-pp-interface>>
#+END_SRC
***** UI - Basic parameters
#+BEGIN_SRC python
  class basic_params:
        def __init__(self):
              self.asdf = 1
#+END_SRC

#+NAME: ui-config-bp-interface
#+BEGIN_SRC python

#+END_SRC

***** UI - Advanced parameters
#+BEGIN_SRC python
  class adv_params:
        def __init__(self):
              self.asdf = 1

#+END_SRC

#+NAME: ui-config-ap-interface
#+BEGIN_SRC python

#+END_SRC

***** UI - Presentation

#+BEGIN_SRC python
  class presentation:
        def __init__(self):
              self.asdf = 1
#+END_SRC

#+NAME: ui-config-pp-interface
#+BEGIN_SRC python

#+END_SRC

*** UI - GUI



** Motor break junction 

** Measurement with Piezo

** Utility functions

* Settings                                                         :noexport:
#+BEGIN_SRC emacs-lisp :export none :results none
(setq org-babel-use-quick-and-dirty-noweb-expansion t)
#+END_SRC




